lane :beta do
  increment_build_number(xcodeproj: "NiyasKitchenInventory.xcodeproj")
  build_app(
    scheme: "NiyasKitchenInventory",
    export_method: "app-store", # or "ad-hoc" if you're testing
    export_options: {
      provisioningProfiles: {
        "test.NiyasKitchenInventory" => "Store2025" # 👈 Your App Store provisioning profile name
      }
    }
  )
  upload_to_testflight
end