
name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:

jobs:
  build-test:
    runs-on: macos-14  # GitHub's macOS runner with Xcode 16
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild \
            -scheme "NiyasKitchenInventory" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Debug \
            build

      - name: Run tests
        run: |
          xcodebuild \
            -scheme "NiyasKitchenInventory" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Debug \
            test
