name: CI

on:
  push:
    branches: [ main, feature, develop ]
  pull_request:
    branches: [ main, feature, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT: NiyasKitchenInventory.xcodeproj
  SCHEME: NiyasKitchenInventory
  TEST_PLAN_NAME: NiyasKitchenInventory   # exact name from the Test Plan editor (top title)
  CONFIGURATION: Debug
  DEVELOPER_DIR: /Applications/Xcode_16.1.app

jobs:
  build-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.1 & show versions
        run: |
          sudo xcode-select -s "$DEVELOPER_DIR"
          xcodebuild -version
          xcrun simctl list runtimes | grep iOS || true
          xcrun simctl list devices | head -n 20

      - name: Set Simulator Destination Dynamically
        id: find-sim
        run: |
          # Find an available iOS simulator (e.g., iPhone 15, latest OS)
          DEVICE_NAME=$(xcrun simctl list devices | grep -E 'iPhone 1[5-9]' | grep -v unavailable | head -n1 | awk -F'[()]' '{print $2}')
          OS_VERSION=$(xcrun simctl list runtimes | grep -E 'iOS [0-9]+' | grep -v unavailable | tail -1 | awk '{print $2}')
          echo "DEVICE_NAME=${DEVICE_NAME:-iPhone 15}" >> $GITHUB_ENV
          echo "OS_VERSION=${OS_VERSION:-latest}" >> $GITHUB_ENV
          echo "DESTINATION=platform=iOS Simulator,name=${DEVICE_NAME:-iPhone 15},OS=${OS_VERSION:-latest}" >> $GITHUB_ENV

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: spm-${{ runner.os }}-

      - name: Resolve SPM Dependencies
        run: xcodebuild -resolvePackageDependencies -project "$PROJECT"

      - name: Build & Test (with Test Plan)
        id: xcode-test
        run: |
          set -euo pipefail
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -testPlan "$TEST_PLAN_NAME" \
            -configuration "$CONFIGURATION" \
            -sdk iphonesimulator \
            -destination "$DESTINATION" \
            -enableCodeCoverage YES \
            clean test \
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Locate latest .xcresult
        if: always()
        id: find-xcresult
        run: |
          set -euo pipefail
          RESULT=$(ls -dt ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult 2>/dev/null | head -n 1 || true)
          echo "result_path=${RESULT}" >> $GITHUB_OUTPUT

      - name: Upload TestResult.xcresult
        if: always() && steps.find-xcresult.outputs.result_path != ''
        uses: actions/upload-artifact@v4
        with:
          name: TestResult.xcresult
          path: ${{ steps.find-xcresult.outputs.result_path }}
          if-no-files-found: ignore

      - name: Helpful failure message
        if: failure()
        run: |
          echo "xcodebuild failed. Download TestResult.xcresult artifact and open it in Xcode for details."
          exit 1
