name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main, feature/** ]
  pull_request:

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (16.1 → 16.0 → default)
        run: |
          if [ -d "/Applications/Xcode_16.1.app" ]; then
            sudo xcode-select -s "/Applications/Xcode_16.1.app"
          elif [ -d "/Applications/Xcode_16.0.app" ]; then
            sudo xcode-select -s "/Applications/Xcode_16.0.app"
          else
            sudo xcode-select -s "/Applications/Xcode.app"
          fi

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Resolve Swift Packages
        run: xcodebuild -project NiyasKitchenInventory.xcodeproj -resolvePackageDependencies

      - name: Build
        run: >
          xcodebuild -project NiyasKitchenInventory.xcodeproj
          -scheme "NiyasKitchenInventory"
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
          -configuration Debug
          build

      - name: Test
        run: >
          xcodebuild -project NiyasKitchenInventory.xcodeproj
          -scheme "NiyasKitchenInventory"
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
          -configuration Debug
          test
