jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s "/Applications/Xcode_16.0.app"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve SPM
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild \
            -scheme "NiyasKitchenInventory" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Debug \
            build

      - name: Test
        run: |
          xcodebuild \
            -scheme "NiyasKitchenInventory" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -configuration Debug \
            test
