name: CI

on:
  push:
    branches: [ main, feature, develop ]
  pull_request:
    branches: [ main, feature, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT: NiyasKitchenInventory.xcodeproj
  SCHEME: NiyasKitchenInventory
  CONFIGURATION: Debug
  DESTINATION: "platform=iOS Simulator,OS=17.4,name=iPhone 15"
  DEVELOPER_DIR: "/Applications/Xcode_16.1.app"

jobs:
  build-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.1 & show versions
        run: |
          sudo xcode-select -s "$DEVELOPER_DIR"
          xcodebuild -version
          xcrun simctl list runtimes | grep "iOS 17.4" || true
          xcrun simctl list devices | grep "iPhone 15" || true

      - name: List repo files & schemes
        run: |
          pwd && ls -la
          echo "::group::xcodebuild -list"
          xcodebuild -list -project "$PROJECT" || true
          echo "::endgroup::"
          echo "::group::Show destinations"
          xcodebuild -project "$PROJECT" -scheme "$SCHEME" -showdestinations || true
          echo "::endgroup::"

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: spm-${{ runner.os }}-

      - name: Resolve SPM Dependencies
        run: xcodebuild -resolvePackageDependencies -project "$PROJECT"

      - name: Build (always produce logs)
        id: build
        shell: bash
        run: |
          set -o pipefail
          mkdir -p build
          DERIVED="$PWD/build/DerivedData"
          XCRESULT="$PWD/build/BuildResult.xcresult"

          echo "DerivedData path: $DERIVED"
          echo "Result bundle:   $XCRESULT"

          # Build. We force no signing and a deterministic derived data path.
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphonesimulator \
            -destination "$DESTINATION" \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath "$DERIVED" \
            -resultBundlePath "$XCRESULT" \
            clean build | tee "build/xcodebuild.log"

          STATUS=${PIPESTATUS[0]}
          echo "build_log_path=$PWD/build/xcodebuild.log" >> "$GITHUB_OUTPUT"
          [ -d "$XCRESULT" ] && echo "xcresult_path=$XCRESULT" >> "$GITHUB_OUTPUT"
          # Show last 100 lines in the job output for quick triage
          echo "::group::tail build log"
          tail -n 100 build/xcodebuild.log || true
          echo "::endgroup::"
          exit $STATUS

      - name: Upload artifacts (logs & xcresult)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ steps.build.outputs.build_log_path }}
            ${{ steps.build.outputs.xcresult_path }}
            build/DerivedData/Logs/Build/*.xcactivitylog
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.xcactivitylog
          if-no-files-found: warn
