name: CI

on:
  workflow_dispatch:              # allows manual runs from the Actions tab
  push:
    branches: [ main, feature/** ]
  pull_request:

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Force Xcode 16.0 (GitHub runner default is 15.4)
      - name: Select Xcode 16.0
        run: sudo xcode-select -s "/Applications/Xcode_16.0.app"

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-xcode16-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-xcode16-

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: >
          xcodebuild -scheme "NiyasKitchenInventory"
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
          -configuration Debug
          build

      - name: Test
        run: >
          xcodebuild -scheme "NiyasKitchenInventory"
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
          -configuration Debug
          test
